# Generated by Django 4.2.4 on 2023-08-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_alter_comment_author_alter_comment_contributor_and_more'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contributor',
        ),
        migrations.RemoveField(
            model_name='anyuser',
            name='is_contributor',
        ),
    ]
