# Generated by Django 4.2.4 on 2023-08-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_alter_comment_author_alter_comment_contributor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='contributor',
        ),
    ]
