# Generated by Django 4.2.4 on 2023-08-21 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_remove_comment_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='affected_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affected_AnyUser', to='Projects.contribution'),
        ),
    ]
