# Generated by Django 4.2.4 on 2023-08-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_alter_contribution_project_alter_contribution_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contributors',
        ),
    ]
